config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  resources :expenses
  devise_for :users
  root 'home#index'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all.where(user_id: current_user.id)
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new
    @business.name = business_params[:name]
    @business.description = business_params[:description]
    @business.user_id = current_user.id
    @business.save

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :user_id)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.haml
= form_for @business do |f|
  - if @business.errors.any?
    #error_explanation
      %h2= "#{pluralize(@business.errors.count, "error")} prohibited this business from being saved:"
      %ul
        - @business.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field.form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .actions.form-group
    = f.submit 'Save', class: "btn btn-primary"

app/views/businesses/edit.html.haml
%h1 Editing business

= render 'form'

= link_to 'Show', @business
\|
= link_to 'Back', businesses_path

app/views/businesses/index.html.haml
%h1.text-center Mis negocios

%table.table.table-striped{:id => "businessTable"}
  %thead
    %tr
      %th Name
      %th Description
      %th User
      %th
      %th
      %th

  %tbody
    - @businesses.each do |business|
      %tr
        %td= business.name
        %td= business.description
        %td= business.user.email
        %td= link_to (fa_icon "eye") ,business, class: "btn btn-primary btn-block"
        %td= link_to (fa_icon "edit"), edit_business_path(business), class: "btn btn-primary btn-block"
        %td= link_to (fa_icon "trash"), business, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-block"

%br

= link_to (fa_icon "plus-circle"), new_business_path, class: "btn btn-primary float-right"

app/views/businesses/new.html.haml
.col-md-12
    %h1 New business

    = render 'form'

    = link_to 'Back', businesses_path

app/views/businesses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @business.name
%p
  %b Description:
  = @business.description
%p
  %b User:
  = @business.user.email

= link_to 'Edit', edit_business_path(@business)
\|
= link_to 'Back', businesses_path