config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  resources :expenses
  devise_for :users
  root 'home#index'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :description, :value, :date)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.haml
= form_for @expense do |f|
  - if @expense.errors.any?
    #error_explanation
      %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
      %ul
        - @expense.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :date
    = f.datetime_select :date
  .actions
    = f.submit 'Save'

app/views/expenses/edit.html.haml
%h1 Editing expense

= render 'form'

= link_to 'Show', @expense
\|
= link_to 'Back', expenses_path

app/views/expenses/index.html.haml
%h1 Listing expenses

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Value
      %th Date
      %th
      %th
      %th

  %tbody
    - @expenses.each do |expense|
      %tr
        %td= expense.name
        %td= expense.description
        %td= expense.value
        %td= expense.date
        %td= link_to 'Show', expense
        %td= link_to 'Edit', edit_expense_path(expense)
        %td= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Expense', new_expense_path

app/views/expenses/new.html.haml
%h1 New expense

= render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @expense.name
%p
  %b Description:
  = @expense.description
%p
  %b Value:
  = @expense.value
%p
  %b Date:
  = @expense.date

= link_to 'Edit', edit_expense_path(@expense)
\|
= link_to 'Back', expenses_path